notifications:
  email:
    recipients:
        - we@batjackson.com
language: ruby
rvm:
 - 2.4.2
install: bundle install --jobs=3 --retry=3
script:
  - "script/test"
deploy:
  provider: s3
  access_key_id: AKIAJ76RZMF4SIG33DMQ
  secret_access_key:
    secure: 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
  region: us-west-1
  bucket: sylvanianforest.com
  acl: bucket_owner_full_control
  on:
    repo: terrajackson/sylvanianforest
    all_branches: true
