notifications:
  email:
    recipients:
    - we@batjackson.com
language: ruby
rvm:
- 2.4.1
install: bundle install --jobs=3 --retry=3
script:
- echo TEST
deploy:
  provider: s3
  access_key_id: AKIA5BOWBE22FGCAV4HN
  secret_access_key:
    secure: bBpN9KtxkjHJZ5/L/g0zaLHglZ2GRkTcDAQmcjiFYF676EeGqt6hP5O1EnMGAHB3/2kt6CASIMbbiP9GG5hZGf/M+Zf/HsfMrmAZjHEOnxMbc9Iigi1Tga2crz7LRHNN2YqGYdmdFZxm2oNDJmk1copbBftVoPWzlaKypPkQ4buFRmUJkgzkEF1ayB4W5qQ7Q6HRiTnov//8sCzlUz96lWexd/MFEf5ZBs2j01I14vEGvVSQvC6gf6VVfkPwSl784zJp0dFUcuUyiUXj0jm4QwCptBNKyaYx9GnDu/RMwjMIRBDiWzCotUFKFGwKD0W5zKuejgInBKk7p67JPQxc9eMmZxRoRvoJ4S9r9IiuBifsrZCn4B/L8rtGny3dZl1UNGjzCsfydt10rtPXg/1c9JVx3+u7FfljNxwLqM8D0DqPQw4w12MZufFJiaIbHKW/YEJMRUNqRLMHsv3nQpZJxl0TEDHnD+yXJN0ZDWfUG+z8GjZdBZHOtA75HTFt0VZjbiDhEwKfQwALh2cfZUKvD3nS8SQQFeKmKlKpmY7a4S6gSXQLbmd2/p5RFvxHdx4lPFn+9siAPm4aRiwq5Sj9Kq+/RT2DXeBcKTTUZDQ47qd/aa3jE7qlt9+CEyuwucTlfTc3o7xgKC/kCU/N6e8vhjd3/mo9xddnQXaBEaRQCfA=
  bucket: sylvaniaforest.com
  region: us-west-1
  acl: bucket_owner_full_control
  on:
    repo: terrajackson/sylvanianforest
